notifications:
  email: false

rvm:
  - 2.1

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - exhibits-team@lists.stanford.edu

env:
  global:
    - JRUBY_OPTS="-J-Xms512m -J-Xmx1024m"
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
language: ruby
